# Generated by Django 5.0.5 on 2024-08-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_hobbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hobbies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
