# Generated by Django 5.0.5 on 2024-08-28 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
