# Generated by Django 5.0.5 on 2024-08-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_cars_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recepie_name', models.CharField(max_length=250)),
                ('recepie_description', models.TextField()),
                ('recepie_image', models.ImageField(upload_to='recipe')),
            ],
        ),
    ]
